{% set name = "aiosmtpd" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiosmtpd-{{ version }}.tar.gz
  sha256: 78d7b14f859ad0e6de252b47f9cf1ca6f1c82a8b0f10a9e39bec7e915a6aa5fe

build:
  skip: true  # [py<36]
  entry_points:
    - aiosmtpd = aiosmtpd.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - atpublic
    - attrs
    - python
    - typing-extensions  # [py<38]

test:
  imports:
    - aiosmtpd
  commands:
    - pip check
    - aiosmtpd --help
  requires:
    - pip

about:
  home: https://aiosmtpd.readthedocs.io/
  summary: aiosmtpd - asyncio based SMTP server
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
