{% set name = "aiosmtpd" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiosmtpd-{{ version }}.tar.gz
  sha256: 5a811826e1a5a06c25ebc3e6c4a704613eb9a1bcf6b78428fbe865f4f6c9a4b8

build:
  noarch: python
  entry_points:
    - aiosmtpd = aiosmtpd.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - atpublic
    - attrs
    - python >={{ python_min }}

test:
  imports:
    - aiosmtpd
  commands:
    - pip check
    - aiosmtpd --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aiosmtpd.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiosmtpd
  summary: aiosmtpd - asyncio based SMTP server
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
