{% set name = "aiosmtpd" %}
{% set version = "1.4.4.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiosmtpd-{{ version }}.tar.gz
  sha256: f9243b7dfe00aaf567da8728d891752426b51392174a34d2cf5c18053b63dcbc

build:
  skip: true  # [py<36]
  entry_points:
    - aiosmtpd = aiosmtpd.main:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python
  run:
    - atpublic
    - attrs
    - python
    - typing-extensions  # [py<38]

test:
  imports:
    - aiosmtpd
  commands:
    - pip check
    - aiosmtpd --help
  requires:
    - pip

about:
  home: https://aiosmtpd.readthedocs.io/
  summary: aiosmtpd - asyncio based SMTP server
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
